# Generated by Django 4.2.9 on 2024-12-09 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(help_text='Physical location of the kiosk', max_length=200)),
                ('theme', models.CharField(choices=[('light', 'Light Theme'), ('dark', 'Dark Theme'), ('custom', 'Custom Theme')], default='light', max_length=20)),
                ('idle_timeout_seconds', models.IntegerField(default=300, help_text='Time in seconds before the kiosk returns to home screen')),
                ('allow_printer', models.BooleanField(default=False, help_text='Allow printing functionality')),
                ('custom_header', models.CharField(blank=True, help_text='Custom header text to display on the kiosk', max_length=200)),
                ('maintenance_mode', models.BooleanField(default=False, help_text='Put kiosk in maintenance mode')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kiosk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='home.kioskclient')),
            ],
            options={
                'verbose_name': 'Kiosk Configuration',
                'verbose_name_plural': 'Kiosk Configurations',
            },
        ),
    ]
