# Generated by Django 4.2.9 on 2024-12-16 16:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_seed_kiosk_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskHealthCheck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_checked', models.DateTimeField(auto_now=True)),
                ('is_healthy', models.BooleanField(default=True)),
                ('health_message', models.TextField(blank=True, null=True)),
                ('kiosk', models.OneToOneField(on_delete=models.CASCADE, related_name='health_check', to='home.kioskclient')),
            ],
            options={
                'verbose_name': 'Kiosk Health Check',
                'verbose_name_plural': 'Kiosk Health Checks',
            },
        ),
    ]
