# Generated by Django 4.2.9 on 2025-01-07 12:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_kioskhealthcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('kiosk_id', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('num_pictures', models.IntegerField()),
                ('status', models.CharField(default='created', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paypal_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paypal_payer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paypal_response', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='kioskhealthcheck',
            options={},
        ),
    ]
