# Generated by Django 4.2.9 on 2025-10-12 20:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_cardimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiosk_id', models.CharField(max_length=64, unique=True)),
                ('secret_key_hash', models.CharField(max_length=128)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled')], default='active', max_length=10)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('allowed_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('allowed_radius', models.IntegerField(default=500)),
                ('hardware_hash', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cardimage',
            name='image',
            field=models.ImageField(upload_to=home.models.card_image_upload_path),
        ),
        migrations.CreateModel(
            name='ReaderDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reader_id', models.CharField(max_length=64, unique=True)),
                ('country', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=16)),
                ('state', models.CharField(max_length=16)),
                ('address', models.CharField(max_length=16)),
                ('postalCode', models.IntegerField(max_length=4)),
                ('name', models.CharField(max_length=100)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('kiosk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readers', to='home.kioskdevice')),
                ('stripe_location_id', models.CharField(max_length=64, blank=False, null=False))
            ],
        ),
    ]
