# Generated by Django 4.2.9 on 2025-10-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_kioskdevice_alter_cardimage_image_readerdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readerdevice',
            name='stripe_location_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
