# Generated by Django 4.2.9 on 2025-10-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_readerdevice_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='paypal_payer_id',
            new_name='stripe_charge_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paypal_payment_id',
            new_name='stripe_payment_intent_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paypal_response',
            new_name='stripe_response',
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='readerdevice',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='readerdevice',
            name='postalCode',
            field=models.CharField(max_length=10),
        ),
    ]
